# Generated by Django 2.2.1 on 2019-07-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
