# Generated by Django 2.2.1 on 2019-08-01 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=60),
        ),
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('Body', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploaded_photos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('Published', 'Published'), ('Drafted', 'Drafted')], default='Drafted', max_length=9)),
                ('slug', models.SlugField(max_length=60)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
