# Generated by Django 2.2.1 on 2019-08-01 15:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0007_auto_20190801_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trends',
            new_name='Trend',
        ),
    ]
